version: '3.5'

# Base configs
x-build-api:
  &default-api-build
  context: ../../.
  dockerfile: docker/images/teamgroundapi/Dockerfile

x-build-database:
  &default-db-build
  context: ../../.
  dockerfile: docker/images/mongo/Dockerfile

x-networks:
  &default-network
  - teamground

x-links:
  &default-links
  - db

x-api-service:
  &default-api-service
  build: *default-api-build
  platform: linux/amd64
  networks: *default-network
  env_file:
    - ../../defaults.env

x-db-service:
  &default-db-service
  build: *default-db-build
  networks: *default-network
  env_file:
    - ../../defaults.env

# application services
services:
  teamground-api:
    << : *default-api-service
    command: sh -c "nodemon --watch './**/*.ts' --exec 'ts-node' index.ts"
    ports:
      - 3000:3000
    depends_on:
      - mongo-db
  
  mongo-db:
    << : *default-db-service
    ports:
      - 27017:27017
    volumes:
      - mongo-db-data:/data/db

# app network
networks:
  teamground:
    name: teamground

# volumes
volumes:
  mongo-db-data:
